import type { BeatCardData } from "@/components/lor/BeatCard";

export const demoBeats: BeatCardData[] = [
  {
    id: "demo-1",
    title: "Midnight Vibes",
    cover_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500&h=500&fit=crop",
    preview_url: null,
    bpm: 90,
    music_key: "F major",
    genre: "lo-fi",
    mood: "chill",
    base_price: 14.99,
    plays_count: 856,
    likes_count: 143,
    producer: { id: "demo-prod", display_name: "League Beats", is_verified: true },
  },
  {
    id: "demo-2",
    title: "Drill Flow",
    cover_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500&h=500&fit=crop",
    preview_url: null,
    bpm: 160,
    music_key: "A minor",
    genre: "drill",
    mood: "dark",
    base_price: 24.99,
    plays_count: 2103,
    likes_count: 267,
    producer: { id: "demo-prod", display_name: "League Beats", is_verified: true },
  },
  {
    id: "demo-3",
    title: "Boom Bap Classic",
    cover_url: "https://images.unsplash.com/photo-1511379938547-c1f69b13d835?w=500&h=500&fit=crop",
    preview_url: null,
    bpm: 95,
    music_key: "G major",
    genre: "boom-bap",
    mood: "soulful",
    base_price: 17.99,
    plays_count: 1534,
    likes_count: 198,
    producer: { id: "demo-prod", display_name: "League Beats", is_verified: true },
  },
];
