/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as BeatsIndexRouteImport } from './routes/beats.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ProducerUploadRouteImport } from './routes/producer.upload'
import { Route as ProducerSubscribeRouteImport } from './routes/producer.subscribe'
import { Route as ProducerDashboardRouteImport } from './routes/producer.dashboard'
import { Route as ProducerContactSubmissionsRouteImport } from './routes/producer.contact-submissions'
import { Route as ProducerContactSettingsRouteImport } from './routes/producer.contact-settings'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BeatsIdRouteImport } from './routes/beats.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminLogoutRouteImport } from './routes/admin.logout'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminSystemSettingsRouteImport } from './routes/admin.system.settings'
import { Route as AdminSystemSecurityRouteImport } from './routes/admin.system.security'
import { Route as AdminSystemAuditLogsRouteImport } from './routes/admin.system.audit-logs'
import { Route as AdminModerationVerificationRouteImport } from './routes/admin.moderation.verification'
import { Route as AdminModerationReportsRouteImport } from './routes/admin.moderation.reports'
import { Route as AdminModerationCommentsRouteImport } from './routes/admin.moderation.comments'
import { Route as AdminContentVideosRouteImport } from './routes/admin.content.videos'
import { Route as AdminContentSongsRouteImport } from './routes/admin.content.songs'
import { Route as AdminContentPlaylistsRouteImport } from './routes/admin.content.playlists'
import { Route as AdminContentGenresRouteImport } from './routes/admin.content.genres'
import { Route as AdminContentBeatsRouteImport } from './routes/admin.content.beats'
import { Route as AdminContentAlbumsRouteImport } from './routes/admin.content.albums'
import { Route as AdminContentManagementBlogRouteImport } from './routes/admin.content-management.blog'
import { Route as AdminContentManagementAnnouncementsRouteImport } from './routes/admin.content-management.announcements'
import { Route as AdminCommunityUsersRouteImport } from './routes/admin.community.users'
import { Route as AdminCommunityArtistsRouteImport } from './routes/admin.community.artists'
import { Route as AdminBusinessPaymentsRouteImport } from './routes/admin.business.payments'
import { Route as AdminBusinessAdvertisementsRouteImport } from './routes/admin.business.advertisements'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatsIndexRoute = BeatsIndexRouteImport.update({
  id: '/beats/',
  path: '/beats/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerUploadRoute = ProducerUploadRouteImport.update({
  id: '/producer/upload',
  path: '/producer/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerSubscribeRoute = ProducerSubscribeRouteImport.update({
  id: '/producer/subscribe',
  path: '/producer/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerDashboardRoute = ProducerDashboardRouteImport.update({
  id: '/producer/dashboard',
  path: '/producer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerContactSubmissionsRoute =
  ProducerContactSubmissionsRouteImport.update({
    id: '/producer/contact-submissions',
    path: '/producer/contact-submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProducerContactSettingsRoute = ProducerContactSettingsRouteImport.update({
  id: '/producer/contact-settings',
  path: '/producer/contact-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatsIdRoute = BeatsIdRouteImport.update({
  id: '/beats/$id',
  path: '/beats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/system/settings',
  path: '/system/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemSecurityRoute = AdminSystemSecurityRouteImport.update({
  id: '/system/security',
  path: '/system/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemAuditLogsRoute = AdminSystemAuditLogsRouteImport.update({
  id: '/system/audit-logs',
  path: '/system/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationVerificationRoute =
  AdminModerationVerificationRouteImport.update({
    id: '/moderation/verification',
    path: '/moderation/verification',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminModerationReportsRoute = AdminModerationReportsRouteImport.update({
  id: '/moderation/reports',
  path: '/moderation/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationCommentsRoute = AdminModerationCommentsRouteImport.update({
  id: '/moderation/comments',
  path: '/moderation/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentVideosRoute = AdminContentVideosRouteImport.update({
  id: '/content/videos',
  path: '/content/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentSongsRoute = AdminContentSongsRouteImport.update({
  id: '/content/songs',
  path: '/content/songs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentPlaylistsRoute = AdminContentPlaylistsRouteImport.update({
  id: '/content/playlists',
  path: '/content/playlists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentGenresRoute = AdminContentGenresRouteImport.update({
  id: '/content/genres',
  path: '/content/genres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentBeatsRoute = AdminContentBeatsRouteImport.update({
  id: '/content/beats',
  path: '/content/beats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentAlbumsRoute = AdminContentAlbumsRouteImport.update({
  id: '/content/albums',
  path: '/content/albums',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentManagementBlogRoute =
  AdminContentManagementBlogRouteImport.update({
    id: '/content-management/blog',
    path: '/content-management/blog',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContentManagementAnnouncementsRoute =
  AdminContentManagementAnnouncementsRouteImport.update({
    id: '/content-management/announcements',
    path: '/content-management/announcements',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCommunityUsersRoute = AdminCommunityUsersRouteImport.update({
  id: '/community/users',
  path: '/community/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityArtistsRoute = AdminCommunityArtistsRouteImport.update({
  id: '/community/artists',
  path: '/community/artists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessPaymentsRoute = AdminBusinessPaymentsRouteImport.update({
  id: '/business/payments',
  path: '/business/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessAdvertisementsRoute =
  AdminBusinessAdvertisementsRouteImport.update({
    id: '/business/advertisements',
    path: '/business/advertisements',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/go-live': typeof GoLiveRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/beats/$id': typeof BeatsIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/live/$id': typeof LiveIdRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/producer/contact-settings': typeof ProducerContactSettingsRoute
  '/producer/contact-submissions': typeof ProducerContactSubmissionsRoute
  '/producer/dashboard': typeof ProducerDashboardRoute
  '/producer/subscribe': typeof ProducerSubscribeRoute
  '/producer/upload': typeof ProducerUploadRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/beats/': typeof BeatsIndexRoute
  '/live/': typeof LiveIndexRoute
  '/admin/business/advertisements': typeof AdminBusinessAdvertisementsRoute
  '/admin/business/payments': typeof AdminBusinessPaymentsRoute
  '/admin/community/artists': typeof AdminCommunityArtistsRoute
  '/admin/community/users': typeof AdminCommunityUsersRoute
  '/admin/content-management/announcements': typeof AdminContentManagementAnnouncementsRoute
  '/admin/content-management/blog': typeof AdminContentManagementBlogRoute
  '/admin/content/albums': typeof AdminContentAlbumsRoute
  '/admin/content/beats': typeof AdminContentBeatsRoute
  '/admin/content/genres': typeof AdminContentGenresRoute
  '/admin/content/playlists': typeof AdminContentPlaylistsRoute
  '/admin/content/songs': typeof AdminContentSongsRoute
  '/admin/content/videos': typeof AdminContentVideosRoute
  '/admin/moderation/comments': typeof AdminModerationCommentsRoute
  '/admin/moderation/reports': typeof AdminModerationReportsRoute
  '/admin/moderation/verification': typeof AdminModerationVerificationRoute
  '/admin/system/audit-logs': typeof AdminSystemAuditLogsRoute
  '/admin/system/security': typeof AdminSystemSecurityRoute
  '/admin/system/settings': typeof AdminSystemSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/go-live': typeof GoLiveRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/beats/$id': typeof BeatsIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/live/$id': typeof LiveIdRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/producer/contact-settings': typeof ProducerContactSettingsRoute
  '/producer/contact-submissions': typeof ProducerContactSubmissionsRoute
  '/producer/dashboard': typeof ProducerDashboardRoute
  '/producer/subscribe': typeof ProducerSubscribeRoute
  '/producer/upload': typeof ProducerUploadRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin': typeof AdminIndexRoute
  '/beats': typeof BeatsIndexRoute
  '/live': typeof LiveIndexRoute
  '/admin/business/advertisements': typeof AdminBusinessAdvertisementsRoute
  '/admin/business/payments': typeof AdminBusinessPaymentsRoute
  '/admin/community/artists': typeof AdminCommunityArtistsRoute
  '/admin/community/users': typeof AdminCommunityUsersRoute
  '/admin/content-management/announcements': typeof AdminContentManagementAnnouncementsRoute
  '/admin/content-management/blog': typeof AdminContentManagementBlogRoute
  '/admin/content/albums': typeof AdminContentAlbumsRoute
  '/admin/content/beats': typeof AdminContentBeatsRoute
  '/admin/content/genres': typeof AdminContentGenresRoute
  '/admin/content/playlists': typeof AdminContentPlaylistsRoute
  '/admin/content/songs': typeof AdminContentSongsRoute
  '/admin/content/videos': typeof AdminContentVideosRoute
  '/admin/moderation/comments': typeof AdminModerationCommentsRoute
  '/admin/moderation/reports': typeof AdminModerationReportsRoute
  '/admin/moderation/verification': typeof AdminModerationVerificationRoute
  '/admin/system/audit-logs': typeof AdminSystemAuditLogsRoute
  '/admin/system/security': typeof AdminSystemSecurityRoute
  '/admin/system/settings': typeof AdminSystemSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/go-live': typeof GoLiveRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/beats/$id': typeof BeatsIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/live/$id': typeof LiveIdRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/producer/contact-settings': typeof ProducerContactSettingsRoute
  '/producer/contact-submissions': typeof ProducerContactSubmissionsRoute
  '/producer/dashboard': typeof ProducerDashboardRoute
  '/producer/subscribe': typeof ProducerSubscribeRoute
  '/producer/upload': typeof ProducerUploadRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/beats/': typeof BeatsIndexRoute
  '/live/': typeof LiveIndexRoute
  '/admin/business/advertisements': typeof AdminBusinessAdvertisementsRoute
  '/admin/business/payments': typeof AdminBusinessPaymentsRoute
  '/admin/community/artists': typeof AdminCommunityArtistsRoute
  '/admin/community/users': typeof AdminCommunityUsersRoute
  '/admin/content-management/announcements': typeof AdminContentManagementAnnouncementsRoute
  '/admin/content-management/blog': typeof AdminContentManagementBlogRoute
  '/admin/content/albums': typeof AdminContentAlbumsRoute
  '/admin/content/beats': typeof AdminContentBeatsRoute
  '/admin/content/genres': typeof AdminContentGenresRoute
  '/admin/content/playlists': typeof AdminContentPlaylistsRoute
  '/admin/content/songs': typeof AdminContentSongsRoute
  '/admin/content/videos': typeof AdminContentVideosRoute
  '/admin/moderation/comments': typeof AdminModerationCommentsRoute
  '/admin/moderation/reports': typeof AdminModerationReportsRoute
  '/admin/moderation/verification': typeof AdminModerationVerificationRoute
  '/admin/system/audit-logs': typeof AdminSystemAuditLogsRoute
  '/admin/system/security': typeof AdminSystemSecurityRoute
  '/admin/system/settings': typeof AdminSystemSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/go-live'
    | '/library'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/search'
    | '/upload'
    | '/admin/analytics'
    | '/admin/help'
    | '/admin/logout'
    | '/auth/callback'
    | '/beats/$id'
    | '/category/$slug'
    | '/live/$id'
    | '/playlists/$id'
    | '/producer/contact-settings'
    | '/producer/contact-submissions'
    | '/producer/dashboard'
    | '/producer/subscribe'
    | '/producer/upload'
    | '/watch/$id'
    | '/admin/'
    | '/beats/'
    | '/live/'
    | '/admin/business/advertisements'
    | '/admin/business/payments'
    | '/admin/community/artists'
    | '/admin/community/users'
    | '/admin/content-management/announcements'
    | '/admin/content-management/blog'
    | '/admin/content/albums'
    | '/admin/content/beats'
    | '/admin/content/genres'
    | '/admin/content/playlists'
    | '/admin/content/songs'
    | '/admin/content/videos'
    | '/admin/moderation/comments'
    | '/admin/moderation/reports'
    | '/admin/moderation/verification'
    | '/admin/system/audit-logs'
    | '/admin/system/security'
    | '/admin/system/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/go-live'
    | '/library'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/search'
    | '/upload'
    | '/admin/analytics'
    | '/admin/help'
    | '/admin/logout'
    | '/auth/callback'
    | '/beats/$id'
    | '/category/$slug'
    | '/live/$id'
    | '/playlists/$id'
    | '/producer/contact-settings'
    | '/producer/contact-submissions'
    | '/producer/dashboard'
    | '/producer/subscribe'
    | '/producer/upload'
    | '/watch/$id'
    | '/admin'
    | '/beats'
    | '/live'
    | '/admin/business/advertisements'
    | '/admin/business/payments'
    | '/admin/community/artists'
    | '/admin/community/users'
    | '/admin/content-management/announcements'
    | '/admin/content-management/blog'
    | '/admin/content/albums'
    | '/admin/content/beats'
    | '/admin/content/genres'
    | '/admin/content/playlists'
    | '/admin/content/songs'
    | '/admin/content/videos'
    | '/admin/moderation/comments'
    | '/admin/moderation/reports'
    | '/admin/moderation/verification'
    | '/admin/system/audit-logs'
    | '/admin/system/security'
    | '/admin/system/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/go-live'
    | '/library'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/search'
    | '/upload'
    | '/admin/analytics'
    | '/admin/help'
    | '/admin/logout'
    | '/auth/callback'
    | '/beats/$id'
    | '/category/$slug'
    | '/live/$id'
    | '/playlists/$id'
    | '/producer/contact-settings'
    | '/producer/contact-submissions'
    | '/producer/dashboard'
    | '/producer/subscribe'
    | '/producer/upload'
    | '/watch/$id'
    | '/admin/'
    | '/beats/'
    | '/live/'
    | '/admin/business/advertisements'
    | '/admin/business/payments'
    | '/admin/community/artists'
    | '/admin/community/users'
    | '/admin/content-management/announcements'
    | '/admin/content-management/blog'
    | '/admin/content/albums'
    | '/admin/content/beats'
    | '/admin/content/genres'
    | '/admin/content/playlists'
    | '/admin/content/songs'
    | '/admin/content/videos'
    | '/admin/moderation/comments'
    | '/admin/moderation/reports'
    | '/admin/moderation/verification'
    | '/admin/system/audit-logs'
    | '/admin/system/security'
    | '/admin/system/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  GoLiveRoute: typeof GoLiveRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BeatsIdRoute: typeof BeatsIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LiveIdRoute: typeof LiveIdRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  ProducerContactSettingsRoute: typeof ProducerContactSettingsRoute
  ProducerContactSubmissionsRoute: typeof ProducerContactSubmissionsRoute
  ProducerDashboardRoute: typeof ProducerDashboardRoute
  ProducerSubscribeRoute: typeof ProducerSubscribeRoute
  ProducerUploadRoute: typeof ProducerUploadRoute
  WatchIdRoute: typeof WatchIdRoute
  BeatsIndexRoute: typeof BeatsIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beats/': {
      id: '/beats/'
      path: '/beats'
      fullPath: '/beats/'
      preLoaderRoute: typeof BeatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/upload': {
      id: '/producer/upload'
      path: '/producer/upload'
      fullPath: '/producer/upload'
      preLoaderRoute: typeof ProducerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/subscribe': {
      id: '/producer/subscribe'
      path: '/producer/subscribe'
      fullPath: '/producer/subscribe'
      preLoaderRoute: typeof ProducerSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/dashboard': {
      id: '/producer/dashboard'
      path: '/producer/dashboard'
      fullPath: '/producer/dashboard'
      preLoaderRoute: typeof ProducerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/contact-submissions': {
      id: '/producer/contact-submissions'
      path: '/producer/contact-submissions'
      fullPath: '/producer/contact-submissions'
      preLoaderRoute: typeof ProducerContactSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/contact-settings': {
      id: '/producer/contact-settings'
      path: '/producer/contact-settings'
      fullPath: '/producer/contact-settings'
      preLoaderRoute: typeof ProducerContactSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beats/$id': {
      id: '/beats/$id'
      path: '/beats/$id'
      fullPath: '/beats/$id'
      preLoaderRoute: typeof BeatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/settings': {
      id: '/admin/system/settings'
      path: '/system/settings'
      fullPath: '/admin/system/settings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/security': {
      id: '/admin/system/security'
      path: '/system/security'
      fullPath: '/admin/system/security'
      preLoaderRoute: typeof AdminSystemSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/audit-logs': {
      id: '/admin/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/admin/system/audit-logs'
      preLoaderRoute: typeof AdminSystemAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation/verification': {
      id: '/admin/moderation/verification'
      path: '/moderation/verification'
      fullPath: '/admin/moderation/verification'
      preLoaderRoute: typeof AdminModerationVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation/reports': {
      id: '/admin/moderation/reports'
      path: '/moderation/reports'
      fullPath: '/admin/moderation/reports'
      preLoaderRoute: typeof AdminModerationReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation/comments': {
      id: '/admin/moderation/comments'
      path: '/moderation/comments'
      fullPath: '/admin/moderation/comments'
      preLoaderRoute: typeof AdminModerationCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/videos': {
      id: '/admin/content/videos'
      path: '/content/videos'
      fullPath: '/admin/content/videos'
      preLoaderRoute: typeof AdminContentVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/songs': {
      id: '/admin/content/songs'
      path: '/content/songs'
      fullPath: '/admin/content/songs'
      preLoaderRoute: typeof AdminContentSongsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/playlists': {
      id: '/admin/content/playlists'
      path: '/content/playlists'
      fullPath: '/admin/content/playlists'
      preLoaderRoute: typeof AdminContentPlaylistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/genres': {
      id: '/admin/content/genres'
      path: '/content/genres'
      fullPath: '/admin/content/genres'
      preLoaderRoute: typeof AdminContentGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/beats': {
      id: '/admin/content/beats'
      path: '/content/beats'
      fullPath: '/admin/content/beats'
      preLoaderRoute: typeof AdminContentBeatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/albums': {
      id: '/admin/content/albums'
      path: '/content/albums'
      fullPath: '/admin/content/albums'
      preLoaderRoute: typeof AdminContentAlbumsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-management/blog': {
      id: '/admin/content-management/blog'
      path: '/content-management/blog'
      fullPath: '/admin/content-management/blog'
      preLoaderRoute: typeof AdminContentManagementBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-management/announcements': {
      id: '/admin/content-management/announcements'
      path: '/content-management/announcements'
      fullPath: '/admin/content-management/announcements'
      preLoaderRoute: typeof AdminContentManagementAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community/users': {
      id: '/admin/community/users'
      path: '/community/users'
      fullPath: '/admin/community/users'
      preLoaderRoute: typeof AdminCommunityUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community/artists': {
      id: '/admin/community/artists'
      path: '/community/artists'
      fullPath: '/admin/community/artists'
      preLoaderRoute: typeof AdminCommunityArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business/payments': {
      id: '/admin/business/payments'
      path: '/business/payments'
      fullPath: '/admin/business/payments'
      preLoaderRoute: typeof AdminBusinessPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business/advertisements': {
      id: '/admin/business/advertisements'
      path: '/business/advertisements'
      fullPath: '/admin/business/advertisements'
      preLoaderRoute: typeof AdminBusinessAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessAdvertisementsRoute: typeof AdminBusinessAdvertisementsRoute
  AdminBusinessPaymentsRoute: typeof AdminBusinessPaymentsRoute
  AdminCommunityArtistsRoute: typeof AdminCommunityArtistsRoute
  AdminCommunityUsersRoute: typeof AdminCommunityUsersRoute
  AdminContentManagementAnnouncementsRoute: typeof AdminContentManagementAnnouncementsRoute
  AdminContentManagementBlogRoute: typeof AdminContentManagementBlogRoute
  AdminContentAlbumsRoute: typeof AdminContentAlbumsRoute
  AdminContentBeatsRoute: typeof AdminContentBeatsRoute
  AdminContentGenresRoute: typeof AdminContentGenresRoute
  AdminContentPlaylistsRoute: typeof AdminContentPlaylistsRoute
  AdminContentSongsRoute: typeof AdminContentSongsRoute
  AdminContentVideosRoute: typeof AdminContentVideosRoute
  AdminModerationCommentsRoute: typeof AdminModerationCommentsRoute
  AdminModerationReportsRoute: typeof AdminModerationReportsRoute
  AdminModerationVerificationRoute: typeof AdminModerationVerificationRoute
  AdminSystemAuditLogsRoute: typeof AdminSystemAuditLogsRoute
  AdminSystemSecurityRoute: typeof AdminSystemSecurityRoute
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessAdvertisementsRoute: AdminBusinessAdvertisementsRoute,
  AdminBusinessPaymentsRoute: AdminBusinessPaymentsRoute,
  AdminCommunityArtistsRoute: AdminCommunityArtistsRoute,
  AdminCommunityUsersRoute: AdminCommunityUsersRoute,
  AdminContentManagementAnnouncementsRoute:
    AdminContentManagementAnnouncementsRoute,
  AdminContentManagementBlogRoute: AdminContentManagementBlogRoute,
  AdminContentAlbumsRoute: AdminContentAlbumsRoute,
  AdminContentBeatsRoute: AdminContentBeatsRoute,
  AdminContentGenresRoute: AdminContentGenresRoute,
  AdminContentPlaylistsRoute: AdminContentPlaylistsRoute,
  AdminContentSongsRoute: AdminContentSongsRoute,
  AdminContentVideosRoute: AdminContentVideosRoute,
  AdminModerationCommentsRoute: AdminModerationCommentsRoute,
  AdminModerationReportsRoute: AdminModerationReportsRoute,
  AdminModerationVerificationRoute: AdminModerationVerificationRoute,
  AdminSystemAuditLogsRoute: AdminSystemAuditLogsRoute,
  AdminSystemSecurityRoute: AdminSystemSecurityRoute,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  GoLiveRoute: GoLiveRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BeatsIdRoute: BeatsIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  LiveIdRoute: LiveIdRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
  ProducerContactSettingsRoute: ProducerContactSettingsRoute,
  ProducerContactSubmissionsRoute: ProducerContactSubmissionsRoute,
  ProducerDashboardRoute: ProducerDashboardRoute,
  ProducerSubscribeRoute: ProducerSubscribeRoute,
  ProducerUploadRoute: ProducerUploadRoute,
  WatchIdRoute: WatchIdRoute,
  BeatsIndexRoute: BeatsIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
